services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    hostname: elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - 'http.cors.allow-origin="*"'
      - xpack.ml.enabled=false
    networks:
      - bha
    ports:
      - '127.0.0.1:9200:9200'
      - '127.0.0.1:9300:9300'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  nginx:
    image: nginx:latest
    hostname: nginx
    ports:
      - '127.0.0.1:8000:8000'
    networks:
      - bha
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  app:
    image: ghcr.io/banned-historical-archives/banned-historical-archives.github.io:latest
    depends_on:
      - elasticsearch
      - nginx
    networks:
      - bha
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - NODE_ENV=development
      - ES_URL=http://elasticsearch:9200
      - ES_USERNAME=elastic
      - ES_PASSWORD=password
      # - node_options="--max-old-space-size=8192"
networks:
  bha:
    driver: bridge
